import { getServerSession } from "next-auth";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../lib/features/cart/cartContext";
import { PromotionProvider } from "../lib/features/promotion/promotionContext";
import { ToastContainer } from "react-toastify";
import SessionProviderClientComponent from "./sessionProviderClientComponent";
import Navbar from "../components/navbar";
import I18nProvider from "./I18nProvider"; // ✅ Bọc toàn bộ app

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="relative min-h-screen pt-16 pb-16">
        <SessionProviderClientComponent session={session}>
          <I18nProvider> {/* 💥 Thêm Provider */}
            <CartProvider>
            <PromotionProvider>
              <Navbar />
              <main className="max-w-screen-lg mx-auto">{children}</main>
              </PromotionProvider>
            </CartProvider>
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar
              closeOnClick
              pauseOnHover
              draggable
              theme="light"
            />
          </I18nProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
